spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///wzy9858blog
      username: root
      password: kdyq1108
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson: #数据库涉及到时间
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #驼峰命名
  type-aliases-package: com.wzy.pojo #起别名
  mapper-locations: classpath:/mapper/*.xml


jwtHelper:
  key: wzy9858
  validTime: 1 #单位 小时